"""Update table file upload

Revision ID: 44058a486af7
Revises: d0b63eec9789
Create Date: 2024-03-30 00:17:29.584194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44058a486af7'
down_revision: Union[str, None] = 'd0b63eec9789'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_upload', sa.Column('time_to_process', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file_upload', 'time_to_process')
    # ### end Alembic commands ###
