"""Create debt and file_upload tables

Revision ID: d0b63eec9789
Revises:
Create Date: 2024-03-28 23:40:22.770367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0b63eec9789'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_upload',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_upload_file_name'), 'file_upload', ['file_name'], unique=False)
    op.create_index(op.f('ix_file_upload_id'), 'file_upload', ['id'], unique=False)
    op.create_table('debt',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('government_id', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('debt_amount', sa.Integer(), nullable=False),
    sa.Column('debt_due_date', sa.Date(), nullable=False),
    sa.Column('file_upload_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['file_upload_id'], ['file_upload.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('debt')
    op.drop_index(op.f('ix_file_upload_id'), table_name='file_upload')
    op.drop_index(op.f('ix_file_upload_file_name'), table_name='file_upload')
    op.drop_table('file_upload')
    # ### end Alembic commands ###
